// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAZNXaORyV8SIIeaLFOwawtn6Wna4uRNw',
    appId: '1:44327915630:web:80c1b1d776a0a414ad967f',
    messagingSenderId: '44327915630',
    projectId: 'contactsapp-b547e',
    authDomain: 'contactsapp-b547e.firebaseapp.com',
    storageBucket: 'contactsapp-b547e.firebasestorage.app',
    measurementId: 'G-Q18GQQZQKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfKqxRBPxjm0nsbArIN4hbd1owrBitTiA',
    appId: '1:44327915630:android:f53a862bcc2b1c6aad967f',
    messagingSenderId: '44327915630',
    projectId: 'contactsapp-b547e',
    storageBucket: 'contactsapp-b547e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF_pOtmB_vmx5TiJ3YZ3hCCzA-w9rjRx8',
    appId: '1:44327915630:ios:99a7514348f931eead967f',
    messagingSenderId: '44327915630',
    projectId: 'contactsapp-b547e',
    storageBucket: 'contactsapp-b547e.firebasestorage.app',
    androidClientId: '44327915630-5nckpnkahiopkb4skfja32meodij71j8.apps.googleusercontent.com',
    iosClientId: '44327915630-lr5ce5ijaecpq6nhmrsdvmma2296r72f.apps.googleusercontent.com',
    iosBundleId: 'com.example.trandangbaoson2224802010933lab4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF_pOtmB_vmx5TiJ3YZ3hCCzA-w9rjRx8',
    appId: '1:44327915630:ios:99a7514348f931eead967f',
    messagingSenderId: '44327915630',
    projectId: 'contactsapp-b547e',
    storageBucket: 'contactsapp-b547e.firebasestorage.app',
    androidClientId: '44327915630-5nckpnkahiopkb4skfja32meodij71j8.apps.googleusercontent.com',
    iosClientId: '44327915630-lr5ce5ijaecpq6nhmrsdvmma2296r72f.apps.googleusercontent.com',
    iosBundleId: 'com.example.trandangbaoson2224802010933lab4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAZNXaORyV8SIIeaLFOwawtn6Wna4uRNw',
    appId: '1:44327915630:web:06211a92e59d3722ad967f',
    messagingSenderId: '44327915630',
    projectId: 'contactsapp-b547e',
    authDomain: 'contactsapp-b547e.firebaseapp.com',
    storageBucket: 'contactsapp-b547e.firebasestorage.app',
    measurementId: 'G-RWDC4NFB7R',
  );
}
